bose_hubbard = "918635ca8e256252637bbdbc50ef909f93b2e7eec2275ba3bf662cb529f3988d"
hubbard_su = "d0e20c521ba1965d1db0e38d828512890e0409bc18ea2a92b0abe21767ea0baf"
2d_ising_partition_function = "86bb41ebdc876c1c10b01dfde934c6888fd7025ccafdee921c02039c3b601d3b"
3d_ising_partition_function = "0555e05299dbe1f7abd403d845b84141684fd5dfc483d560de53850d94ad11a7"
boundary_mps = "7b944fd76d58dad280302d3693fee61bbef3fdf1768ebe21525bb2742d932efe"
heisenberg_su = "01257e88355dd4822bfb380ee1b3ce79b5fea9862f4bee130e89a0d9805e1f3d"
xxz = "80e537be77aabf93835dfe721dacc36b96a64142346c26771ebbb65a1c8f2bac"
fermi_hubbard = "5836dda79371470b21347ad6952a875b4d48195f28ded9af4a1fa0e5b8f04c82"
j1j2_su = "fa3a2389e8dcac62e8477cba85a60236e72402045f1d8658fdf94f17d4d96f2e"
heisenberg = "daa4ba5deb5e47a6357312ac7dd8f97bce5e40cf751284dec03e6b61a7150b21"
