bose_hubbard = "f47aad758f4aa32fa44d7fae8d377ff364e0ee191f468694d4d70c6e3cdbc2b4"
hubbard_su = "95a78abdd94af8ce2219cee2453a74d81f90a8316536c482faebf20563855793"
2d_ising_partition_function = "043e1b0b97197ed611559f4a4683cb8f166c01af82a97f71364f2f5421abe3d2"
3d_ising_partition_function = "baf05623f2b0c496393892be1dfe5c7f72af94ac8c1158db9af5c1aae816c264"
boundary_mps = "430db112b38b4ef30215728f994692e63faa50d085f5c69aad1ee7a7b743431d"
heisenberg_su = "4cedc6a2784417266c007b7ea871c32434e9b837982f846f867a50613f25b15f"
xxz = "9816ec9c07997a7f184be51581075655adc0c8a1a2fffc609ce88d8075a8b7db"
fermi_hubbard = "217d3df2e606e898599dc7c461e04436800f60804add75b0ec5fb5b18d8dcdbf"
j1j2_su = "ccde4117531a26bf679d5a97bcd002974307989fdcc718966ea69a68644d655c"
heisenberg = "136757a5ba5c7a49a803c49395150d1df6bc1fb6eecb29cc20cd968b3d1bf97d"
