bose_hubbard = "f47aad758f4aa32fa44d7fae8d377ff364e0ee191f468694d4d70c6e3cdbc2b4"
hubbard_su = "99f1e8c5aa0aa2b409d4ac1aee754209329b88c96f36cd749381a6a0afc9d9e4"
2d_ising_partition_function = "043e1b0b97197ed611559f4a4683cb8f166c01af82a97f71364f2f5421abe3d2"
3d_ising_partition_function = "baf05623f2b0c496393892be1dfe5c7f72af94ac8c1158db9af5c1aae816c264"
boundary_mps = "430db112b38b4ef30215728f994692e63faa50d085f5c69aad1ee7a7b743431d"
heisenberg_su = "3eb8556d949c0e47e39c679e9e438bc04d3e2a3ffe73e0a682963b37b05f9e91"
xxz = "0231f0c1af2013e8edd9e5c192b108e1ab19a7dca22251c3bde525e3eee2a6aa"
fermi_hubbard = "4997680c826e555557c661e605e1d7d363e0cee15522d0895fa0cfd53b1de001"
j1j2_su = "c00fd13c0be323ab5825af59f3e7b31c3e51d3f65211d3836657b64274504c1c"
heisenberg = "d610c92223d41e296348f9858fab52eacbfe2a578f64f4f8ac4c70d486fb4da2"
